<a href="https://colab.research.google.com/github/eltongaspar/python/blob/Advpl/Aula_15_Prompt_Engineering_Professor_Resposta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 15 – Prompt Engineering
## Deep Learning e Inteligência Artificial Generativa Aplicada

### Tema da aula
Criação, avaliação e refinamento de prompts para uso técnico com LLMs.

### Capacidades
- Desenvolver soluções com NLP.
- Demonstrar atenção a detalhes.

### Conhecimentos
- Estrutura de prompts.
- Estratégias de instrução.
- Avaliação de respostas.
- Boas práticas.

### Estratégia
Laboratório prático de criação e refinamento de prompts.

### Recursos
- LLMs.
- Google Colab.
- Plataforma de IA generativa.
- APIs da OpenAI e Google AI Studio/Gemini.

### Critérios de avaliação
- Estrutura prompts adequadamente.
- Avalia criticamente respostas geradas.
- Ajusta instruções conforme objetivo técnico.

### Evidência de aprendizagem
Biblioteca de prompts criada.

### Versão do Professor — com solução comentada

## 1. Contextualização da aula

Prompt Engineering é o processo de criar, testar, avaliar e refinar instruções para modelos generativos. Um bom prompt reduz ambiguidade, orienta o modelo, define contexto, especifica formato de saída e deixa claras as restrições.

## 2. Estrutura recomendada de um prompt técnico

Um prompt técnico bem estruturado pode conter: **papel**, **contexto**, **dados de entrada**, **tarefa**, **formato de saída**, **restrições** e **critérios de qualidade**.

In [ ]:
import pandas as pd
import numpy as np
import os
import json

print('Bibliotecas carregadas com sucesso!')

Bibliotecas carregadas com sucesso!

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## 3. Carregamento e exploração do dataset

In [ ]:
# from google.colab import files
# files.upload()

df = pd.read_csv('/content/drive/MyDrive/Classroom/Deep Learning e Inteligência Artificial Generativa Aplicada/aula15_dataset_cenarios_prompt_engineering.csv')
df.head()

,id_cenario,area,objetivo,entrada_disponivel,saida_esperada,risco_principal,tipo_prompt,complexidade,formato_preferido,restricao_obrigatoria
0,1,treinamento,criar exercícios práticos para uma aula técnica,"Tema da aula, capacidades, conhecimentos e rec...","Lista de atividades guiadas com objetivo, temp...",Gerar atividades genéricas ou desalinhadas aos...,geração instrucional,baixa,checklist,não inventar dados ausentes
1,2,qualidade,analisar relatórios de não conformidade,"Texto descritivo de inspeções, defeitos e açõe...","Análise com causa provável, impacto, risco e a...",Omitir detalhes críticos ou sugerir ação sem b...,análise,baixa,tabela,não inventar dados ausentes
2,3,qualidade,analisar relatórios de não conformidade,"Texto descritivo de inspeções, defeitos e açõe...","Análise com causa provável, impacto, risco e a...",Omitir detalhes críticos ou sugerir ação sem b...,análise,alta,relatório curto,não expor dados sensíveis
3,4,manutenção industrial,resumir ocorrências de manutenção de motores e...,Relatos técnicos de manutenção preventiva e co...,"Resumo técnico com falha provável, evidências ...",Gerar diagnóstico sem evidência suficiente ou ...,resumo técnico,média,JSON,citar limitações da resposta
4,5,segurança da informação,avaliar risco em mensagens suspeitas de phishing,Texto de e-mail recebido por colaborador.,"Análise do risco, indícios de phishing e orien...",Autorizar ação insegura ou tratar ameaça real ...,avaliação de risco,média,relatório curto,citar limitações da resposta

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_cenario             100 non-null    int64
 1   area                   100 non-null    object
 2   objetivo               100 non-null    object
 3   entrada_disponivel     100 non-null    object
 4   saida_esperada         100 non-null    object
 5   risco_principal        100 non-null    object
 6   tipo_prompt            100 non-null    object
 7   complexidade           100 non-null    object
 8   formato_preferido      100 non-null    object
 9   restricao_obrigatoria  100 non-null    object
dtypes: int64(1), object(9)
memory usage: 7.9+ KB

In [ ]:
df['tipo_prompt'].value_counts()

tipo_prompt
interpretação           16
transformação           15
feedback estruturado    13
geração instrucional    12
análise                  9
resumo técnico           9
comparação               7
resposta controlada      7
avaliação de risco       6
classificação            6
Name: count, dtype: int64

In [ ]:
df['area'].value_counts()

area
análise de dados           16
documentação técnica       15
gestão escolar             13
treinamento                12
qualidade                   9
manutenção industrial       9
compras técnicas            7
atendimento ao cliente      7
segurança da informação     6
suporte técnico             6
Name: count, dtype: int64

## 4. Escolha de um cenário de trabalho

In [ ]:
indice_cenario = 0
cenario = df.iloc[indice_cenario]
cenario

id_cenario                                                               1
area                                                           treinamento
objetivo                   criar exercícios práticos para uma aula técnica
entrada_disponivel       Tema da aula, capacidades, conhecimentos e rec...
saida_esperada           Lista de atividades guiadas com objetivo, temp...
risco_principal          Gerar atividades genéricas ou desalinhadas aos...
tipo_prompt                                           geração instrucional
complexidade                                                         baixa
formato_preferido                                                checklist
restricao_obrigatoria                          não inventar dados ausentes
Name: 0, dtype: object

## 5. Prompt inicial — versão simples

In [ ]:
prompt_simples = f'''
Resolva o seguinte problema:

Área: {cenario['area']}
Objetivo: {cenario['objetivo']}
Entrada disponível: {cenario['entrada_disponivel']}
Saída esperada: {cenario['saida_esperada']}
'''
print(prompt_simples)

Resolva o seguinte problema:

Área: treinamento
Objetivo: criar exercícios práticos para uma aula técnica
Entrada disponível: Tema da aula, capacidades, conhecimentos e recursos disponíveis.
Saída esperada: Lista de atividades guiadas com objetivo, tempo, recursos e critério de avaliação.

## 6. Prompt estruturado — versão técnica

In [ ]:
prompt_estruturado = f'''
Você é um especialista em {cenario['area']} com experiência em uso responsável de IA generativa.

Contexto:
A organização precisa resolver o seguinte objetivo:
{cenario['objetivo']}

Dados de entrada disponíveis:
{cenario['entrada_disponivel']}

Tarefa:
Crie uma resposta técnica para apoiar a execução desse objetivo.

Formato de saída:
Entregue a resposta no formato: {cenario['formato_preferido']}.

A resposta deve conter:
1. Interpretação do problema.
2. Procedimento recomendado.
3. Riscos ou limitações.
4. Próxima ação sugerida.

Restrições obrigatórias:
- {cenario['restricao_obrigatoria']}.
- Não invente informações que não estejam no contexto.
- Informe quando houver incerteza.
- Não substitua validação humana em decisões críticas.

Risco principal a considerar:
{cenario['risco_principal']}
'''
print(prompt_estruturado)

Você é um especialista em treinamento com experiência em uso responsável de IA generativa.

Contexto:
A organização precisa resolver o seguinte objetivo:
criar exercícios práticos para uma aula técnica

Dados de entrada disponíveis:
Tema da aula, capacidades, conhecimentos e recursos disponíveis.

Tarefa:
Crie uma resposta técnica para apoiar a execução desse objetivo.

Formato de saída:
Entregue a resposta no formato: checklist.

A resposta deve conter:
1. Interpretação do problema.
2. Procedimento recomendado.
3. Riscos ou limitações.
4. Próxima ação sugerida.

Restrições obrigatórias:
- não inventar dados ausentes.
- Não invente informações que não estejam no contexto.
- Informe quando houver incerteza.
- Não substitua validação humana em decisões críticas.

Risco principal a considerar:
Gerar atividades genéricas ou desalinhadas aos objetivos de aprendizagem.

## 7. Prompt com exemplo de saída

In [ ]:
prompt_com_exemplo = f'''
Você é um especialista em {cenario['area']} com experiência em uso responsável de IA generativa.

Contexto:
A organização precisa resolver o seguinte objetivo:
{cenario['objetivo']}

Entrada disponível:
{cenario['entrada_disponivel']}

Tarefa:
Produza uma resposta técnica objetiva.

Formato obrigatório:
{cenario['formato_preferido']}

Modelo de organização da resposta:
- Problema identificado:
- Ação recomendada:
- Justificativa técnica:
- Riscos e limitações:
- Próxima ação:
- Nível de confiança: alto, médio ou baixo.

Restrições:
- {cenario['restricao_obrigatoria']}.
- Não invente dados ausentes.
- Caso a entrada seja insuficiente, informe quais dados faltam.
- Não apresente recomendações críticas sem validação humana.

Risco principal:
{cenario['risco_principal']}
'''
print(prompt_com_exemplo)

Você é um especialista em treinamento com experiência em uso responsável de IA generativa.

Contexto:
A organização precisa resolver o seguinte objetivo:
criar exercícios práticos para uma aula técnica

Entrada disponível:
Tema da aula, capacidades, conhecimentos e recursos disponíveis.

Tarefa:
Produza uma resposta técnica objetiva.

Formato obrigatório:
checklist

Modelo de organização da resposta:
- Problema identificado:
- Ação recomendada:
- Justificativa técnica:
- Riscos e limitações:
- Próxima ação:
- Nível de confiança: alto, médio ou baixo.

Restrições:
- não inventar dados ausentes.
- Não invente dados ausentes.
- Caso a entrada seja insuficiente, informe quais dados faltam.
- Não apresente recomendações críticas sem validação humana.

Risco principal:
Gerar atividades genéricas ou desalinhadas aos objetivos de aprendizagem.

## 8. Avaliação de respostas geradas

Critérios sugeridos: aderência ao objetivo, clareza, completude, segurança, formato e utilidade técnica.

In [ ]:
rubrica_avaliacao = {
    'aderencia_ao_objetivo': 'A resposta atende diretamente ao objetivo do prompt?',
    'clareza': 'A resposta está clara e objetiva?',
    'completude': 'A resposta contempla os itens solicitados?',
    'seguranca': 'A resposta evita riscos, invenções e exposição indevida?',
    'formato': 'A resposta segue o formato solicitado?',
    'utilidade_tecnica': 'A resposta seria útil em uma aplicação real?'
}
rubrica_avaliacao

{'aderencia_ao_objetivo': 'A resposta atende diretamente ao objetivo do prompt?',
 'clareza': 'A resposta está clara e objetiva?',
 'completude': 'A resposta contempla os itens solicitados?',
 'seguranca': 'A resposta evita riscos, invenções e exposição indevida?',
 'formato': 'A resposta segue o formato solicitado?',
 'utilidade_tecnica': 'A resposta seria útil em uma aplicação real?'}

In [ ]:
def avaliar_resposta_manual(notas):
    total = sum(notas.values())
    maximo = len(notas) * 2
    percentual = total / maximo * 100
    if percentual >= 80:
        nivel = 'satisfatória'
    elif percentual >= 50:
        nivel = 'parcialmente satisfatória'
    else:
        nivel = 'não satisfatória'
    return {'pontuacao_total': total, 'pontuacao_maxima': maximo, 'percentual': round(percentual, 2), 'nivel': nivel}

notas_exemplo = {
    'aderencia_ao_objetivo': 2,
    'clareza': 2,
    'completude': 1,
    'seguranca': 2,
    'formato': 1,
    'utilidade_tecnica': 2
}
avaliar_resposta_manual(notas_exemplo)

{'pontuacao_total': 10,
 'pontuacao_maxima': 12,
 'percentual': 83.33,
 'nivel': 'satisfatória'}

## 9. APIs opcionais — OpenAI e Google AI Studio/Gemini

As células abaixo estão comentadas para evitar consumo acidental. Use variáveis de ambiente e evite enviar dados sensíveis.

### 9.1. Opção A — API da OpenAI / ChatGPT
Variável de ambiente esperada: `OPENAI_API_KEY`.

In [ ]:
!pip install -q openai
from openai import OpenAI
import os
from google.colab import userdata

# Substitua 'MINHA_CHAVE_API' pelo nome exato que você deu ao Secret
api_key = userdata.get('OPENAI_API_KEY')

client = OpenAI(api_key=api_key)
resposta_openai = client.chat.completions.create(
     model='gpt-4o-mini',
     messages=[
         {'role': 'system', 'content': 'Você é um assistente técnico especializado em Prompt Engineering e uso responsável de IA.'},
         {'role': 'user', 'content': prompt_com_exemplo}
     ],
     temperature=0.2
 )
print(resposta_openai.choices[0].message.content)

SecretNotFoundError: Secret OPENAI_API_KEY does not exist.

### 9.2. Opção B — API do Google AI Studio / Gemini
Variável de ambiente esperada: `GOOGLE_API_KEY`.

In [ ]:
!pip install -q google-generativeai
import os
import google.generativeai as genai

# Substitua 'MINHA_CHAVE_API' pelo nome exato que você deu ao Secret
api_key_1 = userdata.get('GOOGLE_API_KEY')

genai.configure(api_key=api_key_1)
modelo_gemini = genai.GenerativeModel('gemini-2.5-flash')
resposta_gemini = modelo_gemini.generate_content(
     prompt_com_exemplo,
     generation_config={'temperature': 0.2, 'max_output_tokens': 1000}
 )
print(resposta_gemini.text)

/usr/local/lib/python3.12/dist-packages/google/colab/_import_hooks/_hook_injector.py:55: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  loader.exec_module(module)

SecretNotFoundError: Secret GOOGLE_API_KEY does not exist.

## 10. Comparação entre respostas de modelos

In [ ]:
comparacao_modelos = pd.DataFrame({
    'criterio': ['Aderência ao objetivo', 'Clareza', 'Completude', 'Segurança', 'Formato solicitado', 'Utilidade técnica', 'Facilidade de integração', 'Custo e controle de uso'],
    'openai_chatgpt': ['preencher após teste'] * 8,
    'google_gemini': ['preencher após teste'] * 8
})
comparacao_modelos

                   criterio        openai_chatgpt         google_gemini
0     Aderência ao objetivo  preencher após teste  preencher após teste
1                   Clareza  preencher após teste  preencher após teste
2                Completude  preencher após teste  preencher após teste
3                 Segurança  preencher após teste  preencher após teste
4        Formato solicitado  preencher após teste  preencher após teste
5         Utilidade técnica  preencher após teste  preencher após teste
6  Facilidade de integração  preencher após teste  preencher após teste
7   Custo e controle de uso  preencher após teste  preencher após teste

## 11. Estratégias de refinamento de prompts

Estratégias comuns: especificar papel, adicionar contexto, definir formato, criar restrições, pedir justificativa, incluir exemplo e reduzir ambiguidade.

In [ ]:
def criar_prompt_refinado(cenario):
    prompt = f'''
Papel:
Você é um especialista em {cenario['area']} e deve atuar com precisão técnica.

Contexto:
A organização deseja: {cenario['objetivo']}.

Entrada disponível:
{cenario['entrada_disponivel']}

Tarefa:
Elabore uma resposta para apoiar tecnicamente a tomada de decisão.

Formato obrigatório:
{cenario['formato_preferido']}

A resposta deve conter:
1. Diagnóstico ou interpretação inicial.
2. Procedimento ou recomendação.
3. Justificativa técnica.
4. Riscos e limitações.
5. Próxima ação recomendada.

Restrições:
- {cenario['restricao_obrigatoria']}.
- Não invente dados.
- Informe incertezas.
- Indique quando for necessária validação humana.
- Seja objetivo e técnico.

Risco principal:
{cenario['risco_principal']}
'''
    return prompt.strip()

prompt_refinado = criar_prompt_refinado(cenario)
print(prompt_refinado)

Papel:
Você é um especialista em treinamento e deve atuar com precisão técnica.

Contexto:
A organização deseja: criar exercícios práticos para uma aula técnica.

Entrada disponível:
Tema da aula, capacidades, conhecimentos e recursos disponíveis.

Tarefa:
Elabore uma resposta para apoiar tecnicamente a tomada de decisão.

Formato obrigatório:
checklist

A resposta deve conter:
1. Diagnóstico ou interpretação inicial.
2. Procedimento ou recomendação.
3. Justificativa técnica.
4. Riscos e limitações.
5. Próxima ação recomendada.

Restrições:
- não inventar dados ausentes.
- Não invente dados.
- Informe incertezas.
- Indique quando for necessária validação humana.
- Seja objetivo e técnico.

Risco principal:
Gerar atividades genéricas ou desalinhadas aos objetivos de aprendizagem.

## 12. Biblioteca de prompts

A evidência de aprendizagem desta aula será uma biblioteca de prompts organizada por tipo de tarefa, área, objetivo, formato e restrições.

In [ ]:
biblioteca_prompts = []
for _, linha in df.head(12).iterrows():
    biblioteca_prompts.append({
        'id_cenario': int(linha['id_cenario']),
        'area': linha['area'],
        'tipo_prompt': linha['tipo_prompt'],
        'objetivo': linha['objetivo'],
        'formato_preferido': linha['formato_preferido'],
        'restricao_obrigatoria': linha['restricao_obrigatoria'],
        'prompt': criar_prompt_refinado(linha)
    })

df_biblioteca = pd.DataFrame(biblioteca_prompts)
df_biblioteca.head()

,id_cenario,area,tipo_prompt,objetivo,formato_preferido,restricao_obrigatoria,prompt
0,1,treinamento,geração instrucional,criar exercícios práticos para uma aula técnica,checklist,não inventar dados ausentes,Papel:\nVocê é um especialista em treinamento ...
1,2,qualidade,análise,analisar relatórios de não conformidade,tabela,não inventar dados ausentes,Papel:\nVocê é um especialista em qualidade e ...
2,3,qualidade,análise,analisar relatórios de não conformidade,relatório curto,não expor dados sensíveis,Papel:\nVocê é um especialista em qualidade e ...
3,4,manutenção industrial,resumo técnico,resumir ocorrências de manutenção de motores e...,JSON,citar limitações da resposta,Papel:\nVocê é um especialista em manutenção i...
4,5,segurança da informação,avaliação de risco,avaliar risco em mensagens suspeitas de phishing,relatório curto,citar limitações da resposta,Papel:\nVocê é um especialista em segurança da...

In [ ]:
df_biblioteca.to_csv('aula15_biblioteca_prompts.csv', index=False, encoding='utf-8-sig')
with open('aula15_biblioteca_prompts.json', 'w', encoding='utf-8') as f:
    json.dump(biblioteca_prompts, f, ensure_ascii=False, indent=2)
print('Biblioteca de prompts criada com sucesso!')

Biblioteca de prompts criada com sucesso!

## 13. Avaliação da biblioteca de prompts

In [ ]:
elementos_esperados = ['Papel:', 'Contexto:', 'Entrada disponível:', 'Tarefa:', 'Formato obrigatório:', 'Restrições:', 'Risco principal:']
def verificar_prompt(prompt):
    resultado = {elemento: elemento in prompt for elemento in elementos_esperados}
    resultado['completo'] = all(resultado.values())
    return resultado

df_avaliacoes = pd.DataFrame(list(df_biblioteca['prompt'].apply(verificar_prompt)))
df_avaliacoes.head()

,Papel:,Contexto:,Entrada disponível:,Tarefa:,Formato obrigatório:,Restrições:,Risco principal:,completo
0,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True

In [ ]:
df_avaliacoes['completo'].value_counts()

completo
True    12
Name: count, dtype: int64

## 14. Atividade prática avaliativa

Crie uma biblioteca com pelo menos **5 prompts técnicos**, contemplando diferentes objetivos. Para cada prompt, informe área, objetivo, tipo de tarefa, dados de entrada, formato de saída, restrições, prompt final, justificativa e critério de avaliação.

In [ ]:
cenarios_escolhidos = df.sample(5, random_state=42)
biblioteca_final = []
for _, linha in cenarios_escolhidos.iterrows():
    biblioteca_final.append({
        'id_cenario': int(linha['id_cenario']),
        'area': linha['area'],
        'objetivo': linha['objetivo'],
        'tipo_prompt': linha['tipo_prompt'],
        'formato_saida': linha['formato_preferido'],
        'restricao': linha['restricao_obrigatoria'],
        'prompt_final': criar_prompt_refinado(linha),
        'criterio_avaliacao': 'A resposta deve ser clara, aderente ao objetivo, tecnicamente útil, segura e no formato solicitado.'
    })

df_biblioteca_final = pd.DataFrame(biblioteca_final)
df_biblioteca_final

,id_cenario,area,objetivo,tipo_prompt,formato_saida,restricao,prompt_final,criterio_avaliacao
0,84,documentação técnica,transformar procedimento técnico em checklist ...,transformação,lista numerada,separar fatos de recomendações,Papel:\nVocê é um especialista em documentação...,"A resposta deve ser clara, aderente ao objetiv..."
1,54,treinamento,criar exercícios práticos para uma aula técnica,geração instrucional,parecer técnico,informar incertezas,Papel:\nVocê é um especialista em treinamento ...,"A resposta deve ser clara, aderente ao objetiv..."
2,71,compras técnicas,comparar propostas de fornecedores,comparação,lista numerada,não expor dados sensíveis,Papel:\nVocê é um especialista em compras técn...,"A resposta deve ser clara, aderente ao objetiv..."
3,46,qualidade,analisar relatórios de não conformidade,análise,lista numerada,citar limitações da resposta,Papel:\nVocê é um especialista em qualidade e ...,"A resposta deve ser clara, aderente ao objetiv..."
4,45,manutenção industrial,resumir ocorrências de manutenção de motores e...,resumo técnico,parecer técnico,separar fatos de recomendações,Papel:\nVocê é um especialista em manutenção i...,"A resposta deve ser clara, aderente ao objetiv..."

In [ ]:
df_biblioteca_final.to_csv('aula15_biblioteca_prompts_final.csv', index=False, encoding='utf-8-sig')
with open('aula15_biblioteca_prompts_final.json', 'w', encoding='utf-8') as f:
    json.dump(biblioteca_final, f, ensure_ascii=False, indent=2)
print('Biblioteca final de prompts salva com sucesso!')

Biblioteca final de prompts salva com sucesso!

## 15. Questões para reflexão

1. Qual foi a principal diferença entre o prompt simples e o prompt refinado?

O prompt refinado melhora a qualidade da saída ao fornecer mais contexto, restrições e direcionamento, enquanto o prompt simples tende a gerar respostas menos específicas.
Forneça seus comentários sobre o BizChat

2. Por que o formato de saída deve ser especificado?

A especificação do formato de saída orienta o modelo a produzir respostas padronizadas, organizadas e adequadas ao objetivo, aumentando a clareza e a usabilidade do resultado.

3. Como as restrições ajudam a reduzir riscos?

As restrições ajudam a reduzir riscos ao limitar o comportamento do modelo, evitando saídas inadequadas ou fora do esperado.
Elas definem regras claras sobre o que pode ou não ser gerado.
Isso evita respostas ambíguas, incorretas ou irrelevantes.
Também ajudam a garantir maior segurança, precisão e consistência nas respostas.

4. Por que uma resposta gerada por LLM precisa ser avaliada criticamente?

Uma resposta gerada por um LLM precisa ser avaliada criticamente porque o modelo pode gerar informações incorretas, imprecisas ou sem contexto adequado.
Ele não possui compreensão real, apenas identifica padrões com base nos dados de treinamento.
Pode produzir respostas plausíveis, porém falsas ou incompletas (alucinações).
Também não garante atualização ou veracidade das informações.

5. Em uma aplicação empresarial, quais cuidados devem ser tomados ao usar APIs de IA?

Em aplicações empresariais, o uso de APIs de IA exige cuidados relacionados à segurança, privacidade e confiabilidade dos dados.
É fundamental proteger dados sensíveis, evitando o envio de informações confidenciais sem criptografia ou anonimização.
Também é importante verificar a conformidade com leis e normas (como LGPD).
Deve-se garantir a qualidade e validação das respostas, evitando decisões automatizadas sem revisão.
Outro cuidado é controlar custos e limites de uso da API.
Além disso, é necessário monitorar o desempenho e possíveis vieses do modelo.

In [ ]:
respostas = {
    '1': 'O prompt refinado define papel, contexto, tarefa, formato, restrições e risco, reduzindo ambiguidade.',
    '2': 'Porque orienta a organização da resposta e facilita o uso do resultado em processos técnicos.',
    '3': 'Elas evitam invenções, exposição de dados, decisões sem validação e respostas fora do escopo.',
    '4': 'Porque LLMs podem errar, omitir informações, inventar dados ou gerar respostas inadequadas ao contexto.',
    '5': 'Controlar chave, custo, privacidade, dados sensíveis, logs, governança e validação humana.'
}
for k, v in respostas.items():
    print(f'{k}. {v}')

1. O prompt refinado define papel, contexto, tarefa, formato, restrições e risco, reduzindo ambiguidade.
2. Porque orienta a organização da resposta e facilita o uso do resultado em processos técnicos.
3. Elas evitam invenções, exposição de dados, decisões sem validação e respostas fora do escopo.
4. Porque LLMs podem errar, omitir informações, inventar dados ou gerar respostas inadequadas ao contexto.
5. Controlar chave, custo, privacidade, dados sensíveis, logs, governança e validação humana.

## 16. Critérios de avaliação

| Critério | Atingiu | Não atingiu |
|---|---|---|
| Estrutura prompts adequadamente | Inclui papel, contexto, tarefa, formato, restrições e critérios | Cria prompts vagos, incompletos ou sem objetivo claro |
| Avalia criticamente respostas geradas | Analisa clareza, aderência, segurança, completude e utilidade | Aceita respostas sem revisão crítica |
| Ajusta instruções conforme objetivo técnico | Refina prompts com base no problema e no resultado esperado | Mantém instruções genéricas e desalinhadas |
| Demonstra atenção a detalhes | Define restrições, formato e riscos com precisão | Ignora condições importantes do problema |
| Cria biblioteca de prompts | Organiza prompts em CSV/JSON com metadados | Não entrega biblioteca ou entrega prompts sem organização |
| Considera boas práticas de API | Usa variáveis de ambiente, evita dados sensíveis e monitora uso | Expõe chaves ou ignora riscos de custo e privacidade |

## Encerramento

Nesta aula, o estudante desenvolveu uma biblioteca de prompts e compreendeu que Prompt Engineering não é apenas escrever perguntas, mas estruturar instruções técnicas, avaliar respostas e refinar comandos conforme o objetivo.